name = "Wavefronts"
uuid = "5a5f1f2e-54ce-422a-b05d-abd9e7c2d134"
authors = ["Hugo Levy-Falk"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
